### ISSUE TITLE
Issues on Forge for export due to the data folder

### ISSUE THREAD

**Issue by sytone** [sytone/foundry-vtt-journal-sync#2]
https://discord.com/channels/170995199584108546/722566083499786352/732257090940436490

 @sytone I was using your Journals Sync and really like it, there are some issues with using it on Forge because it uses "data" in the code. Is it possible to change the settings to use the filepicker and save out the source object to pick locations other than data to save in?

**Comment by sytone** [comment]
Using DirectoryPicker from vtta-tokenizer to test the value returned is '[data] journal-sync' need to look at upload functions to see how to translate.

**Comment by LimpingNinja** [comment]
You can actually use the vtta-tokenizer implementation (directorypicker). I tested it and it worked. 



I just added a pull-request: https://github.com/sytone/foundry-vtt-journal-sync/pull/3  , it doesn't use the DirectoryPicker from vtta-tokenizer but the parse method will look familiar. I have tested the P/R on the Forge. Since it is not using a DirectoryPicker a user will need to be savvy and specify:

[forgevtt] journal-sync/

When setting it up on the Forge. If the directory picker is added later and the setting type changed to an object for the MarkDownSourcePath then that part will be automated. 

Please note, the P/R is not just this fix, if you don't want the other fix then you may need to be selective.

**Comment by LimpingNinja** [comment]
Close pull request, see some issues on import. [edit] My recent commit now has changes that fix the import as well, please take a look on my fork for changes. If you want a PR, I can create a new one.

**Comment by sytone** [comment]
Thanks for the work. here please make a PR so we can get this updated and released.

**Comment by LimpingNinja** [comment]
Thanks, do you want me to separate it out from the other change (Import/Export World?) I’ll create the push on what I have right now, if you want to separate the rest out instead I’ll fork a new branch and handle it tonight. I’m Sweden time zone :)

**Comment by sytone** [comment]
no, it can all go. Happy to make this as useful as possible to all.

**Comment by sytone** [comment]
Merged changes in.
